sudo: false
language: python
python:
  - 3.8
install:
  - pip install -U pip setuptools
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install coveralls
script:
  - pip install -e .
  - py.test -v
after_success:
  - coveralls
notifications:
  email: false
